### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CircuitSacul** [CircuitSacul/starboard-rs#1]
A list of stuff I want to implement to make sure I have this all figured out.

## Autostar Channels
 - [ ] Autostar channel settings
       - Ability to edit
       - Actually respect
       - Validation
 - [ ] Autocomplete for autostar channel names
 - [ ] Baseline permission checks

## Owner Commands
Use a prefix-based system for owner commands. Can't do eval but can do other stuff.

## Premium
 - [ ] Implement premium commands
       - `/owner give-credits`: Give a user credits
       - `/premium info`: Show premium info, including user's credits & autoredeem
       - `/premium redeem`: Convert X*3 credits into X months of guild premium
       - `/premium server`: Show the current servers premium status
       - `/premium autoredeem enabled: <bool>`: Enable/disable autoredeem for a server
       - `/premium locks [move|refresh]`: Move/refresh premium locks
 - [ ] Implement background task to find and "expire" expired premium
       - Check autoredeem first, obviously
 - [ ] Implement patreon system
       - Fetch data from patreon API
       - Background task + member join events for supporter/patron role
